sudo: enabled
dist: trusty

language: python
python:
 - "2.7"
 - "3.5"

install:
  - pip install pytest-cov
  - pip install codecov
  - pip install tox-travis

script:
 - tox
 - echo $(ls)

after_success:
  - codecov -t "$CODECOV_TOKEN"
