sudo: enabled
dist: xenial

language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"

install:
 - pip install pytest --upgrade
 - pip install pytest-cov
 - pip install wheel codecov coverage

script:
 - pytest --cov-report xml --cov=json_checker

after_success:
 - codecov -t "$CODECOV_TOKEN"

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: ${PIPY_USER}
  password: ${PIPY_PASS}
  on:
    tags: true
