sudo: enabled
dist: trusty

language: python
python:
 - "2.7"
 - "3.5"

install:
  - pip install pytest-cov
  - pip install wheel codecov coverage
  - pip install tox-travis

script:
 - py.test --cov-report xml --cov=checker
 - echo $(ls)
 - echo $(ls tests)

after_success: coverage combine && codecov -t "$CODECOV_TOKEN"
