version: '3'

services:

  lint:
    build: .
    container_name: json_checker.lint
    entrypoint: |
      flake8 json_checker tests

  tests:
    build: .
    container_name: json_checker.tests
    entrypoint: |
      pytest tests -v --cov-report xml --cov=json_checker
      codecov -t "$CODECOV_TOKEN"

  upload-pypi:
    build: .
    container_name: json_checker.pypi
    entrypoint: |
      python setup.py sdist bdist_wheel
#      twine upload --repository-url https://upload.pypi.org/legacy/ dist/*